version: "3"
services:
  web:
    image: nginx:latest
    ports:
    - "8080:80"
    volumes:
    - ../src:/site
    - ./nginx/site.conf:/etc/nginx/conf.d/default.conf
    networks:
      - web-network
  php:
    build: .
    volumes:
    - ../src:/site
    networks:
      - web-network
  db:
    image: mysql:5.7
    ports:
    - "3306:3306"
    volumes:
    - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: prestashop_dev
    networks:
      - web-network
volumes:
  mysql-data:
networks:
  web-network:
    driver: bridge